### PR TITLE
lib/hdfs_mkdir: fix require

### PR DESCRIPTION
**Pull request by leopaul36**

### CODE REVIEW

**Comment by wdavidw** [comment]
I disagree, hive shouldnt be enabled by default in spark but auto-wired if present

**Comment by wdavidw** [comment]
in my environnement (only masson+ambari), it generates the following error in configure:

```
TypeError: Cannot read property 'hive.server2.authentication' of undefined
    at Proxy.module.exports (/home/wdavidw/projects/ryba/ryba/hive/beeline/configure.coffee.md:31:30)
```

**Comment by leopaul36** [comment]
The original problem was that oozie/server's `spark_client: implicit: true, module: 'ryba/spark/client'` caused spark/client/check to fail because of the lack of hive configuration, hence the modification.

[This](https://github.com/leopaul36/ryba/commit/0198c4d71a0033b9e518a0e22d0c5a7531b21ef2) fixed the error you're referring.

Please let me know if this is an acceptable fix.

**Comment by wdavidw** [comment]
Hive does not require Tez, Tez does not require Hive. Implicit can't be enabled. When fixing an issue, you must clearly state its original (oozie in this case), if necessary describes the reason and fix its cause, not its consequences. Which check is failing, "Check Shell (Hive SQL)" ? Then you can either run the check conditionnaly only if hive is enabled on all YARN NMs (is that the cause of your problem?) or throw an Error if you consider the hive action as a requirement in oozie.

**Comment by lucasbak** [comment]
To fix the issue , the oozie/server/install should only install spark rpm to get the spark-jars. Only the jars are needed for the spark shared lib.
Now if oozie server needs spark-defaults.conf files to get spark settings, you can write only the spark-default.con file by importing its valine from spark a spark/client context.

**Comment by damienclaveau** [comment]
Please keep in mind that the the shared lib setup process needs a spark-conf dir designated by the property oozie.service.SparkConfigurationService.spark.configuration

**Pull request merged**
