### PR TITLE
#49: hbase: isolate conf dirs

### PR DESCRIPTION
**Pull request by lucasbak**
Review changes and fix before any merge.

### CODE REVIEW

**Comment by wdavidw** [comment]
overall, this seems pretty good. i can only see one issue with the "hbase-env.sh" generation. In HB and HRS, you're using both render and write. Using render is great, this was on the roadmap. but you dont need to call write after, i'm pretty sure rendering also do search/replace as well since it rely on write (templating is actully done inside write). also, it seems like client use write and doesnt render the file and you'll end up ith an empty "java_home", just change this.

**Comment by lucasbak** [comment]
Okay, I will do the modifications and tell you when its ready

**Comment by wdavidw** [comment]
they are minor, if it works then good job

**Comment by lucasbak** [comment]
Yes, this branch has been tested on  a clean install

**Pull request merged**
