### PR TITLE
ssl: refactor

### PR DESCRIPTION
**Pull request by leopaul36**
Most of the modules are impacted, I already tested it with my configuration but if someone could go ahead and test it with a fresh install of `ryba-env-metal` before merging that would be great.

### CODE REVIEW

**Comment by wdavidw** [comment]
Could you squash your 2 commits ?

**Comment by leopaul36** [comment]
What do you mean by squash ?

**Comment by wdavidw** [comment]
I saw you had two commit so i asked u to merge them, however one is a merge so i dont know if it'll work

**Comment by leopaul36** [comment]
I think I managed to do it, new PR incomin

**Pull request closed without merging**
